import { Property, User, PropertyType, PropertyStatus, BarterProposal, ProposalStatus, VerificationStatus } from './types';

export const MOCK_USERS: User[] = [
  { id: 'user-1', name: 'علی رضایی', profilePicture: 'https://i.pravatar.cc/150?u=user1', city: 'تهران' },
  { id: 'user-2', name: 'زهرا احمدی', profilePicture: 'https://i.pravatar.cc/150?u=user2', city: 'مشهد' },
  { id: 'user-3', name: 'محمد حسینی', profilePicture: 'https://i.pravatar.cc/150?u=user3', city: 'تبریز' },
];

// Centralized placeholder for the currently logged-in user
export const CURRENT_USER = MOCK_USERS[0];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'آپارتمان لوکس در الهیه',
    description: 'یک واحد آپارتمان مدرن با طراحی بی‌نظیر و ویوی ابدی شهر تهران. دارای سه خواب مستر، سالن اجتماعات و استخر.',
    owner: MOCK_USERS[0],
    propertyType: PropertyType.APARTMENT,
    address: 'خیابان فرشته، کوچه شبدیز',
    city: 'تهران',
    area: 250,
    rooms: 3,
    yearBuilt: 1399,
    images: ['https://picsum.photos/seed/prop1/800/600', 'https://picsum.photos/seed/prop1-2/800/600', 'https://picsum.photos/seed/prop1-3/800/600'],
    estimatedValue: 75000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['ویلا در شمال', 'خودرو لوکس'],
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: 'prop-2',
    title: 'ویلای دوبلکس استخردار در مشهد',
    description: 'ویلایی زیبا در منطقه طرقبه مشهد با فضای سبز دلنشین، استخر آب گرم و امکانات کامل رفاهی.',
    owner: MOCK_USERS[1],
    propertyType: PropertyType.VILLA,
    address: 'طرقبه، بلوار امام رضا',
    city: 'مشهد',
    area: 400,
    rooms: 4,
    yearBuilt: 1401,
    images: ['https://picsum.photos/seed/prop2/800/600', 'https://picsum.photos/seed/prop2-2/800/600'],
    estimatedValue: 40000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['آپارتمان در تهران', 'زمین تجاری'],
    verificationStatus: VerificationStatus.UNVERIFIED,
  },
  {
    id: 'prop-3',
    title: 'زمین تجاری بر بلوار اصلی',
    description: 'قطعه زمین با موقعیت استثنایی برای ساخت مجتمع تجاری یا اداری در یکی از بهترین مناطق تبریز.',
    owner: MOCK_USERS[2],
    propertyType: PropertyType.LAND,
    address: 'ولیعصر، خیابان شهریار',
    city: 'تبریز',
    area: 1000,
    rooms: 0,
    yearBuilt: 0,
    images: ['https://picsum.photos/seed/prop3/800/600'],
    estimatedValue: 120000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['چند واحد آپارتمان', 'ملک کلنگی'],
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: 'prop-4',
    title: 'آپارتمان نقلی در مرکز شیراز',
    description: 'یک واحد دو خوابه تمیز و بازسازی شده در مرکز شهر شیراز، دسترسی عالی به مترو و مراکز خرید.',
    owner: MOCK_USERS[1],
    propertyType: PropertyType.APARTMENT,
    address: 'خیابان زند، کوچه ۴۵',
    city: 'شیراز',
    area: 90,
    rooms: 2,
    yearBuilt: 1395,
    images: ['https://picsum.photos/seed/prop4/800/600', 'https://picsum.photos/seed/prop4-2/800/600'],
    estimatedValue: 8000000000,
    status: PropertyStatus.PENDING_DEAL,
    barterPreferences: ['خانه ویلایی در حومه شیراز'],
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: 'prop-5',
    title: 'مغازه فعال در بازار یزد',
    description: 'مغازه تجاری در قلب بازار سنتی یزد با پاخور عالی و مناسب برای انواع مشاغل.',
    owner: MOCK_USERS[0],
    propertyType: PropertyType.COMMERCIAL,
    address: 'بازار خان',
    city: 'یزد',
    area: 40,
    rooms: 0,
    yearBuilt: 1380,
    images: ['https://picsum.photos/seed/prop5/800/600'],
    estimatedValue: 15000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['آپارتمان در یزد', 'خودرو'],
    verificationStatus: VerificationStatus.UNVERIFIED,
  },
   {
    id: 'prop-6',
    title: 'ویلا سنتی در طبس',
    description: 'خانه ویلایی با معماری سنتی و حیاط بزرگ در شهر طبس، مناسب برای اقامت و سرمایه‌گذاری.',
    owner: MOCK_USERS[2],
    propertyType: PropertyType.VILLA,
    address: 'میدان امام',
    city: 'طبس',
    area: 300,
    rooms: 3,
    yearBuilt: 1385,
    images: ['https://picsum.photos/seed/prop6/800/600'],
    estimatedValue: 5000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['آپارتمان در مشهد'],
    verificationStatus: VerificationStatus.UNVERIFIED,
  },
  {
    id: 'prop-7',
    title: 'زمین مسکونی در اقلید',
    description: 'قطعه زمین مناسب ساخت ویلا در منطقه خوش آب و هوای اقلید فارس.',
    owner: MOCK_USERS[1],
    propertyType: PropertyType.LAND,
    address: 'بلوار شریعتی',
    city: 'اقلید',
    area: 500,
    rooms: 0,
    yearBuilt: 0,
    images: ['https://picsum.photos/seed/prop7/800/600'],
    estimatedValue: 2000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['خودرو', 'آپارتمان کوچک در شیراز'],
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: 'prop-8',
    title: 'آپارتمان در سعادت آباد تهران',
    description: 'واحدی خوش نقشه در یکی از بهترین فرعی‌های سعادت آباد با نورگیر عالی و دسترسی بی‌نظیر.',
    owner: MOCK_USERS[0],
    propertyType: PropertyType.APARTMENT,
    address: 'سعادت آباد، علامه شمالی',
    city: 'تهران',
    area: 150,
    rooms: 3,
    yearBuilt: 1398,
    images: ['https://picsum.photos/seed/prop8/800/600'],
    estimatedValue: 45000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['ویلای لواسان', 'زمین در شمال'],
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: 'prop-9',
    title: 'واحد تجاری در برج آرمیتاژ مشهد',
    description: 'واحد تجاری شیک در یکی از مدرن‌ترین برج‌های تجاری مشهد، مناسب برای برندهای معتبر.',
    owner: MOCK_USERS[1],
    propertyType: PropertyType.COMMERCIAL,
    address: 'بلوار هفت تیر',
    city: 'مشهد',
    area: 80,
    rooms: 0,
    yearBuilt: 1400,
    images: ['https://picsum.photos/seed/prop9/800/600'],
    estimatedValue: 30000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['آپارتمان در مشهد', 'زمین'],
    verificationStatus: VerificationStatus.UNVERIFIED,
  },
  {
    id: 'prop-10',
    title: 'خانه ویلایی در معالی آباد شیراز',
    description: 'خانه ویلایی دلباز با حیاط مشجر و قابلیت سکونت یا ساخت مجدد در بهترین نقطه معالی آباد.',
    owner: MOCK_USERS[2],
    propertyType: PropertyType.VILLA,
    address: 'معالی آباد، خیابان دوستان',
    city: 'شیراز',
    area: 350,
    rooms: 4,
    yearBuilt: 1388,
    images: ['https://picsum.photos/seed/prop10/800/600'],
    estimatedValue: 25000000000,
    status: PropertyStatus.EXCHANGED,
    barterPreferences: [],
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: 'prop-11',
    title: 'آپارتمان کوچک در صفائیه یزد',
    description: 'سوئیت آپارتمان مناسب برای زوج‌های جوان یا سرمایه‌گذاری در منطقه اعیان‌نشین یزد.',
    owner: MOCK_USERS[0],
    propertyType: PropertyType.APARTMENT,
    address: 'صفائیه، بلوار دانشگاه',
    city: 'یزد',
    area: 75,
    rooms: 1,
    yearBuilt: 1396,
    images: ['https://picsum.photos/seed/prop11/800/600'],
    estimatedValue: 6000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['خودرو'],
    verificationStatus: VerificationStatus.UNVERIFIED,
  },
    {
    id: 'prop-12',
    title: 'زمین کشاورزی حومه تبریز',
    description: 'زمین حاصلخیز با سهمیه آب، مناسب برای کشاورزی و ایجاد باغ در نزدیکی تبریز.',
    owner: MOCK_USERS[2],
    propertyType: PropertyType.LAND,
    address: 'جاده باسمنج',
    city: 'تبریز',
    area: 5000,
    rooms: 0,
    yearBuilt: 0,
    images: ['https://picsum.photos/seed/prop12/800/600'],
    estimatedValue: 10000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['آپارتمان در تبریز'],
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: 'prop-13',
    title: 'پنت هاوس دوبلکس در فرمانیه',
    description: 'پنت هاوس رویایی با روف گاردن اختصاصی و ویوی ۳۶۰ درجه در یکی از لوکس‌ترین برج‌های فرمانیه.',
    owner: MOCK_USERS[0],
    propertyType: PropertyType.APARTMENT,
    address: 'فرمانیه شرقی',
    city: 'تهران',
    area: 400,
    rooms: 4,
    yearBuilt: 1402,
    images: ['https://picsum.photos/seed/prop13/800/600', 'https://picsum.photos/seed/prop13-2/800/600'],
    estimatedValue: 150000000000,
    status: PropertyStatus.PENDING_DEAL,
    barterPreferences: ['ملک تجاری', 'چندین واحد آپارتمان'],
    verificationStatus: VerificationStatus.UNVERIFIED,
  },
  {
    id: 'prop-14',
    title: 'سوئیت مبله در اصفهان',
    description: 'یک سوئیت شیک و مبله در نزدیکی میدان نقش جهان، مناسب برای سرمایه‌گذاری و اجاره روزانه.',
    owner: MOCK_USERS[1],
    propertyType: PropertyType.APARTMENT,
    address: 'خیابان استانداری',
    city: 'اصفهان',
    area: 50,
    rooms: 1,
    yearBuilt: 1399,
    images: ['https://picsum.photos/seed/prop14/800/600'],
    estimatedValue: 4500000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['خودرو', 'زمین کوچک'],
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: 'prop-15',
    title: 'ملک کلنگی در مرکز مشهد',
    description: 'ملک با متراژ بالا و موقعیت عالی برای ساخت و ساز در مرکز شهر مشهد.',
    owner: MOCK_USERS[2],
    propertyType: PropertyType.VILLA,
    address: 'خیابان بهار',
    city: 'مشهد',
    area: 600,
    rooms: 5,
    yearBuilt: 1375,
    images: ['https://picsum.photos/seed/prop15/800/600'],
    estimatedValue: 50000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['آپارتمان نوساز'],
    verificationStatus: VerificationStatus.UNVERIFIED,
  },
  {
    id: 'prop-16',
    title: 'باغ ویلا در تفت یزد',
    description: 'باغ ویلای سرسبز با انواع درختان میوه و ویلای شیک در منطقه ییلاقی تفت.',
    owner: MOCK_USERS[0],
    propertyType: PropertyType.VILLA,
    address: 'جاده ده بالا',
    city: 'یزد',
    area: 2000,
    rooms: 2,
    yearBuilt: 1395,
    images: ['https://picsum.photos/seed/prop16/800/600'],
    estimatedValue: 18000000000,
    status: PropertyStatus.AVAILABLE,
    barterPreferences: ['آپارتمان در یزد'],
    verificationStatus: VerificationStatus.VERIFIED,
  }
];

export const MOCK_PROPOSALS: BarterProposal[] = [
    {
        id: 'proposal-1',
        proposer: MOCK_USERS[1],
        proposerProperty: MOCK_PROPERTIES[1],
        receiver: MOCK_USERS[0],
        receiverProperty: MOCK_PROPERTIES[0],
        status: ProposalStatus.PENDING,
        message: 'سلام، برای تهاتر ویلای مشهد با آپارتمان شما در تهران تمایل دارم. در صورت نیاز برای مابه‌التفاوت هم مذاکره می‌کنیم.',
        cashDifference: 10000000000, // Proposer offers to PAY 10B Toman
    },
    {
        id: 'proposal-2',
        proposer: MOCK_USERS[0],
        proposerProperty: MOCK_PROPERTIES[4],
        receiver: MOCK_USERS[2],
        receiverProperty: MOCK_PROPERTIES[2],
        status: ProposalStatus.REJECTED,
        message: 'برای تهاتر مغازه یزد با بخشی از ارزش زمین شما پیشنهاد دارم.',
    }
];